# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18519925fe6d76c2469a81c9e30878f700c74bb09d6c12ff281c4197b3019f9ef990bde6ad264af2866b7a7808b47903299fd0a373fc287aaf20e7b8e0b97e25

test:
  secret_key_base: 32a74f5ad0b0e38bda46c6ceabc68e36dabb3b3523bdd4419c21b96761581cc4bf0b9c98f343744f707188a52945b076c0a2920ea8732c082e63d3cae5bf4a85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
